# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03d1e7111dd5eb82395811e83bdce3f8852f854e34f309ca52706ff81c180392ec632d0af06a07ff0eb0ce3303f908c90fc83c84a1d67812869e9c05face0f98

test:
  secret_key_base: d92098cb159e3630615561155e149111dff2f848f1904ea829a70681801febedf154daabfa4f90ccb6fd26ae7060ff31644c9403c94f511bb488ee6307fade55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
